### ISSUE TITLE
display results to slack user from db

### ISSUE THREAD

**Issue by mi-lee** [hrx/slack-private-archiver#3]
- [ ] server receives search request and keyword from #2 
- [ ] server searches db for keyword
- [ ] server responds with results
- [ ] slack displays results or link to results page

My thought for MVP on this is to dump the message json to an html file and provide the link to people when they [search for old messages](https://github.com/hrx-org/slack-private-archiver/issues/2). So raw not pretty, but it'd be pretty easy for someone with design skills to improve on it from there. @dting made a nice one here: https://github.com/dting/slack-archive-viewer

Another option is just to dump lines of text back to the user in slack via only-user-visible message in channel or via DM.

I suggest going with the simplest (MVP) option. -@mLuby

**Comment by mLuby** [comment]
My thought for MVP on this is to dump the message json to an html file and provide the link to people when they [search for old messages](https://github.com/hrx-org/slack-private-archiver/issues/2).

So raw not pretty, but it'd be pretty easy for someone with design skills to improve on it from there.

**Comment by mi-lee** [comment]
Great idea. I'd label this as 'future ideas' or something but I don't have permission to add labels.

**Comment by mLuby** [comment]
oh whoops. let me see how to fix that

**Comment by mi-lee** [comment]
now I do. thanks!

**Comment by mLuby** [comment]
Closing as old.
