### ISSUE TITLE
where to store messages?

### ISSUE THREAD

**Issue by mLuby** [hrx/slack-private-archiver#4]
# questions
1. what rate of storage do we expect? 100MB/day?
2. what's our budget? $0?

# storage options
a. mongo (firebase?)
b. sql
c. file system
d key/value

**Comment by cehsu** [comment]
Postgres will be the source of truth for archived messages. Still need to determine if we are going to use it as a traditional RDBMS, or use it’s newer document store feature.
We plan to explore paid options/services (e.g. Elasticsearch) if the free options (heroku/postgres) are not sufficient for our purposes.
