### ISSUE TITLE
document workflow

### ISSUE THREAD

**Issue by cehsu** [hrx/slack-private-archiver#7]

**Comment by Anoninnyc** [comment]
http://bit.ly/2fqr0oK

**Comment by Anoninnyc** [comment]
Hi All!, 
The proposed git workflow is available on "Proposed Workflow" tab of the "HRX Questions for the Community...." spreadsheet.
It's _very_ light on details- I'd like to mold it with the feedback I get. 
Thx, 
Krishan

**Comment by mLuby** [comment]
@Anoninnyc keep in mind this repo _and_ that link are both totally public.

I suggest we keep this in github. Maybe start a PR to add to `README.md` or add `CONTRIBUTING.md` so we can comment on it?

**Comment by mLuby** [comment]
I turned on master branch protection and the requirement that a branch be reviewed before merge. I like having github enforce our practices. :)

**Comment by Anoninnyc** [comment]
Added bare bones contributing.md, as per @mLuby suggestion.
